[versions]
# Add a version for the Compose Bill of Materials (BOM)
compose-bom = "2024.04.00" # Use the latest version available
# You can add separate versions for compose-ui, compose-material3, etc.
# but using the BOM is easier.


[libraries]
# Add the Compose BOM
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }

# Add the specific Compose libraries
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.9.0" } # Use latest

# Optional: You can create a bundle for easy addition
[bundles]
compose = [
    "androidx-ui",
    "androidx-ui-graphics",
    "androidx-material3",
    "androidx-activity-compose"
]